### ISSUE TITLE
use cases

### ISSUE THREAD

**Issue by jpowell** [AaronLasseigne/unifig#2]
@AaronLasseigne what's your other use-cases? is there a list of providers you're marching towards? What was the example that sparked this?

**Comment by AaronLasseigne** [comment]
I was fixing a performance issue in Figaro and I noticed that it's basically unmaintained. I started looking at options and decided to see if I could make something better.

An MVP to play with was this plus `unifig-rails` and `unifig-env`. It seems to work well.

Other providers would be:
 - Rails secrets
 - Google Secret Manager
 - AWS Secrets Manager
 - any other place that stuff is held
